FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y \
    software-properties-common  \
    git \
    wget \
    curl \
    build-essential \
    gcc \
    libgl1-mesa-glx 

RUN pip install --upgrade pip setuptools wheel

WORKDIR /workspace

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt pip
# Install Qdrant
RUN pip install qdrant-client==1.16.2
RUN wget https://github.com/qdrant/qdrant/releases/download/v1.16.3/qdrant-x86_64-unknown-linux-gnu.tar.gz \
    && tar -xvzf qdrant-x86_64-unknown-linux-gnu.tar.gz \
    && mv qdrant /usr/local/bin/ \
    && rm qdrant-x86_64-unknown-linux-gnu.tar.gz
RUN python -c "import nltk; nltk.download('punkt'); nltk.download('wordnet'); nltk.download('averaged_perceptron_tagger')"

RUN pip uninstall -y enum34
RUN mkdir -p /workspace/data /workspace/models /qdrant/storage
COPY qdrant_config.yaml /workspace/
COPY llm_server.py /workspace/

EXPOSE 8888 8001 8002 6333
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
# Start script
COPY start_services.sh /workspace/
RUN chmod +x /workspace/start_services.sh
# CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token='whatever123'"]
CMD ["/workspace/start_services.sh"]